[package]
name = "neso-gui"
version = "0.1.0"
authors = ["Jeffrey Xiao <jeffrey.xiao1998@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32"
log = "0.4"
neso = "0.5"
sdl2 = "0.31.0"
serde = "1.0"
serde_derive = "1.0"
simplelog = "0.5.3"
toml = "0.4"
